name: trawallet_final_version
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  flutter_facebook_auth: ^6.1.1
  ionicons: ^0.2.1
  cloud_firestore: ^5.6.12
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  encrypt: ^5.0.1
  flutter_secure_storage: ^9.2.4
  file_picker: ^8.0.0
  local_auth: ^3.0.0
  image_picker: ^1.0.7
  open_filex: ^4.5.0
  cached_network_image: ^3.3.1
  timeago: ^3.6.0
  supabase_flutter: ^2.10.3
  url_launcher: ^6.2.0
  geolocator: ^10.1.0 # GPS location
  geocoding: ^2.1.1
  flutter_svg: ^1.1.1
  intl: ^0.18.1
  photo_view: ^0.15.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/trawallet_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
